# Generated by Django 5.2.15 on 2026-06-28 20:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("marcxml_bib", "MARCXML bibliographic"),
                            ("dublin_core", "Dublin Core"),
                            ("csv_patrons", "CSV patrons"),
                            ("csv_items", "CSV items"),
                            ("csv_holdings", "CSV holdings"),
                            ("csv_acquisitions", "CSV acquisitions"),
                            ("csv_fees", "CSV fees"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("result_file", models.FileField(blank=True, upload_to="exports/")),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("error_report", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["export_type", "status"],
                        name="interop_exp_export__c96715_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "created_at"],
                        name="interop_exp_request_26d56e_idx",
                    ),
                ],
            },
        ),
    ]
