# Generated by Django 5.2.15 on 2026-06-28 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("vocabularies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
                ("timezone", models.CharField(default="Asia/Taipei", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("shelving_area", models.CharField(blank=True, max_length=255)),
                ("is_public", models.BooleanField(default=True)),
                ("circulation_policy", models.CharField(blank=True, max_length=64)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="holdings.branch",
                    ),
                ),
            ],
            options={
                "unique_together": {("branch", "code")},
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("public_note", models.TextField(blank=True)),
                ("staff_note", models.TextField(blank=True)),
                ("textual_holdings", models.TextField(blank=True)),
                ("access_policy", models.CharField(blank=True, max_length=128)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holdings",
                        to="holdings.branch",
                    ),
                ),
                (
                    "call_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vocabularies.callnumber",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="catalog.instance",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holdings",
                        to="holdings.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("barcode", models.CharField(max_length=128, unique=True)),
                ("copy_number", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("on_loan", "On loan"),
                            ("on_hold", "On hold"),
                            ("in_process", "In process"),
                            ("missing", "Missing"),
                            ("lost", "Lost"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="in_process",
                        max_length=32,
                    ),
                ),
                ("inventory_number", models.CharField(blank=True, max_length=128)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("acquired_at", models.DateField(blank=True, null=True)),
                ("last_inventory_at", models.DateTimeField(blank=True, null=True)),
                ("due_back_at", models.DateTimeField(blank=True, null=True)),
                ("item_note", models.TextField(blank=True)),
                (
                    "holding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="holdings.holding",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="holdings_it_status_759286_idx"
                    ),
                    models.Index(
                        fields=["barcode"], name="holdings_it_barcode_a6d874_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="holding",
            index=models.Index(
                fields=["branch", "location"], name="holdings_ho_branch__edab78_idx"
            ),
        ),
    ]
