# Generated by Django 5.2.15 on 2026-06-28 17:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("licensor", models.CharField(blank=True, max_length=255)),
                ("starts_at", models.DateField(blank=True, null=True)),
                ("ends_at", models.DateField(blank=True, null=True)),
                ("terms", models.JSONField(blank=True, default=dict)),
                ("document", models.FileField(blank=True, upload_to="licenses/")),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElectronicResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=512)),
                (
                    "resource_kind",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("ejournal", "Electronic journal"),
                            ("ebook", "Electronic book"),
                            ("package", "Package"),
                        ],
                        max_length=32,
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=255)),
                ("access_url", models.URLField(blank=True)),
                ("coverage", models.JSONField(blank=True, default=dict)),
                ("authentication_method", models.CharField(blank=True, max_length=128)),
                ("identifiers", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="erm.license",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resource_kind", "is_active"],
                        name="erm_electro_resourc_6987b4_idx",
                    ),
                    models.Index(fields=["title"], name="erm_electro_title_ce1955_idx"),
                ],
            },
        ),
    ]
