# Generated by Django 5.2.15 on 2026-06-28 19:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acquisitions", "0002_fund_acquisitionorderline_branch_and_more"),
        ("catalog", "0001_initial"),
        ("erm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("proxy_prefix", models.URLField()),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="electronicresource",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="electronic_resources",
                to="catalog.instance",
            ),
        ),
        migrations.AddField(
            model_name="electronicresource",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="electronicresource",
            name="resource_mode",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("hybrid", "Hybrid"),
                    ("local", "Local"),
                ],
                default="online",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="electronicresource",
            name="status",
            field=models.CharField(
                choices=[
                    ("trial", "Trial"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("cancelled", "Cancelled"),
                ],
                default="trial",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licenses",
                to="acquisitions.invoice",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="renewal_notice_days",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licenses",
                to="acquisitions.vendor",
            ),
        ),
        migrations.CreateModel(
            name="AccessUrl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("label", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("is_primary", models.BooleanField(default=False)),
                ("requires_proxy", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_urls",
                        to="erm.electronicresource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[
                            ("full_text", "Full text"),
                            ("abstracting", "Abstracting"),
                            ("indexing", "Indexing"),
                        ],
                        default="full_text",
                        max_length=24,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("embargo", models.CharField(blank=True, max_length=128)),
                ("coverage_note", models.TextField(blank=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverages",
                        to="erm.electronicresource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LicenseTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "term_type",
                    models.CharField(
                        choices=[
                            ("walk_in_users", "Walk-in users"),
                            ("remote_access", "Remote access"),
                            ("interlibrary_loan", "Interlibrary loan"),
                            ("course_reserves", "Course reserves"),
                            ("concurrent_users", "Concurrent users"),
                        ],
                        max_length=32,
                    ),
                ),
                ("allowed", models.BooleanField(default=True)),
                ("limit_value", models.CharField(blank=True, max_length=128)),
                ("note", models.TextField(blank=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_terms",
                        to="erm.license",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trial",
                        max_length=16,
                    ),
                ),
                ("starts_at", models.DateField(blank=True, null=True)),
                ("ends_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="erm.license",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="acquisitions.vendor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="electronicresource",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="erm.package",
            ),
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.URLField(blank=True)),
                ("admin_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platforms",
                        to="acquisitions.vendor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="package",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packages",
                to="erm.platform",
            ),
        ),
        migrations.AddField(
            model_name="electronicresource",
            name="platform_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="erm.platform",
            ),
        ),
        migrations.AddIndex(
            model_name="electronicresource",
            index=models.Index(
                fields=["status", "is_public"], name="erm_electro_status_c7ec20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="electronicresource",
            index=models.Index(fields=["resource_mode"], name="erm_electro_resourc_ddd0d3_idx"),
        ),
        migrations.AddField(
            model_name="accessurl",
            name="proxy_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_urls",
                to="erm.proxyconfig",
            ),
        ),
        migrations.AddIndex(
            model_name="coverage",
            index=models.Index(
                fields=["coverage_type", "start_date", "end_date"],
                name="erm_coverag_coverag_582321_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="licenseterm",
            index=models.Index(
                fields=["term_type", "allowed"], name="erm_license_term_ty_7b339d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="licenseterm",
            unique_together={("license", "term_type")},
        ),
        migrations.AddIndex(
            model_name="platform",
            index=models.Index(fields=["code"], name="erm_platfor_code_1bfa4a_idx"),
        ),
        migrations.AddIndex(
            model_name="platform",
            index=models.Index(fields=["name"], name="erm_platfor_name_057eaa_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["status", "ends_at"], name="erm_package_status_655f1b_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["name"], name="erm_package_name_9fe9d5_idx"),
        ),
        migrations.AddIndex(
            model_name="accessurl",
            index=models.Index(
                fields=["is_primary", "requires_proxy"],
                name="erm_accessu_is_prim_69e213_idx",
            ),
        ),
    ]
