# Generated by Django 5.2.15 on 2026-06-28 20:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataQualityRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("issue_count", models.PositiveIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_report", models.TextField(blank=True)),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_quality_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=96)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(max_length=512)),
                ("entity_id", models.CharField(blank=True, max_length=64)),
                ("entity_label", models.CharField(blank=True, max_length=512)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="core.dataqualityrun",
                    ),
                ),
            ],
            options={
                "ordering": ["code", "entity_label"],
            },
        ),
        migrations.AddIndex(
            model_name="dataqualityrun",
            index=models.Index(
                fields=["status", "started_at"], name="core_dataqu_status_258382_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataqualityissue",
            index=models.Index(fields=["run", "code"], name="core_dataqu_run_id_843695_idx"),
        ),
        migrations.AddIndex(
            model_name="dataqualityissue",
            index=models.Index(
                fields=["severity", "created_at"], name="core_dataqu_severit_634023_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataqualityissue",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="core_dataqu_entity__4cf9fc_idx",
            ),
        ),
    ]
