# Generated by Django 5.2.15 on 2026-06-28 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authorities", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarcRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("bibliographic", "Bibliographic"),
                            ("authority", "Authority"),
                            ("holdings", "Holdings"),
                        ],
                        max_length=32,
                    ),
                ),
                ("raw_iso2709", models.BinaryField(blank=True, null=True)),
                ("marcxml", models.TextField(blank=True)),
                ("parsed_json", models.JSONField(blank=True, default=dict)),
                ("leader", models.CharField(blank=True, max_length=24)),
                ("control_number", models.CharField(blank=True, max_length=128)),
                ("source", models.CharField(blank=True, max_length=128)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "authority_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marc_records",
                        to="authorities.authorityrecord",
                    ),
                ),
                (
                    "bibliographic_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marc_records",
                        to="catalog.bibliographicrecord",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["format_type", "control_number"],
                        name="marc_marcre_format__e0ebc1_idx",
                    ),
                    models.Index(
                        fields=["validation_status"],
                        name="marc_marcre_validat_cbf4f6_idx",
                    ),
                ],
            },
        ),
    ]
