# Generated by Django 5.2.15 on 2026-06-28 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorities", "0001_initial"),
        ("catalog", "0001_initial"),
        ("marc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarcImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=128)),
                (
                    "import_format",
                    models.CharField(
                        choices=[
                            ("iso2709", "ISO2709"),
                            ("marcxml", "MARCXML"),
                            ("json", "JSON MARC"),
                        ],
                        max_length=16,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsed", "Parsed"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("valid_count", models.PositiveIntegerField(default=0)),
                ("invalid_count", models.PositiveIntegerField(default=0)),
                ("conflict_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marc_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarcImportRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField()),
                ("raw_payload", models.TextField(blank=True)),
                ("parsed_json", models.JSONField(blank=True, default=dict)),
                ("mapped_json", models.JSONField(blank=True, default=dict)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsed", "Parsed"),
                            ("invalid", "Invalid"),
                            ("conflict", "Conflict"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("control_number", models.CharField(blank=True, max_length=128)),
                ("conflict_reason", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="marc.marcimportbatch",
                    ),
                ),
                (
                    "bibliographic_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_records",
                        to="catalog.bibliographicrecord",
                    ),
                ),
                (
                    "marc_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_records",
                        to="marc.marcrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="AuthorityLinkSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("marc_tag", models.CharField(max_length=8)),
                ("label", models.CharField(max_length=512)),
                ("authority_type", models.CharField(max_length=32)),
                ("role", models.CharField(blank=True, max_length=64)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("created", "Created provisional authority"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "matched_authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marc_import_suggestions",
                        to="authorities.authorityrecord",
                    ),
                ),
                (
                    "import_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authority_suggestions",
                        to="marc.marcimportrecord",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="marcimportbatch",
            index=models.Index(
                fields=["status", "created_at"], name="marc_marcim_status_3a0ccc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marcimportbatch",
            index=models.Index(
                fields=["source", "import_format"], name="marc_marcim_source_378e51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marcimportrecord",
            index=models.Index(
                fields=["batch", "status"], name="marc_marcim_batch_i_3d9a91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marcimportrecord",
            index=models.Index(
                fields=["control_number"], name="marc_marcim_control_8f6c97_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marcimportrecord",
            unique_together={("batch", "sequence")},
        ),
        migrations.AddIndex(
            model_name="authoritylinksuggestion",
            index=models.Index(
                fields=["import_record", "status"],
                name="marc_author_import__80a22d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authoritylinksuggestion",
            index=models.Index(
                fields=["label", "authority_type"], name="marc_author_label_f08f73_idx"
            ),
        ),
    ]
