# Generated by Django 5.2.15 on 2026-06-28 21:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authorities", "0003_alter_authorityrecord_unique_together_and_more"),
        ("catalog", "0001_initial"),
        ("holdings", "0001_initial"),
        ("marc", "0002_marcimportbatch_marcimportrecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarcMatchCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("bibliographic", "Bibliographic record"),
                            ("authority", "Authority record"),
                            ("holding", "Holding"),
                            ("instance", "Instance"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_id", models.CharField(max_length=64)),
                ("match_rule", models.CharField(max_length=96)),
                ("confidence", models.PositiveIntegerField(default=0)),
                ("reason", models.CharField(max_length=512)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("selected", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-confidence", "match_rule"],
            },
        ),
        migrations.AddField(
            model_name="marcimportrecord",
            name="authority_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_records",
                to="authorities.authorityrecord",
            ),
        ),
        migrations.AddField(
            model_name="marcimportrecord",
            name="format_type",
            field=models.CharField(
                choices=[
                    ("bibliographic", "Bibliographic"),
                    ("authority", "Authority"),
                    ("holdings", "Holdings"),
                ],
                default="bibliographic",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="marcimportrecord",
            name="holding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marc_import_records",
                to="holdings.holding",
            ),
        ),
        migrations.AddField(
            model_name="marcimportrecord",
            name="resolution_action",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="marcimportrecord",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marcimportrecord",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_marc_import_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marcrecord",
            name="holding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marc_records",
                to="holdings.holding",
            ),
        ),
        migrations.AddIndex(
            model_name="marcimportrecord",
            index=models.Index(
                fields=["format_type", "status"], name="marc_marcim_format__d889b9_idx"
            ),
        ),
        migrations.AddField(
            model_name="marcmatchcandidate",
            name="import_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_candidates",
                to="marc.marcimportrecord",
            ),
        ),
        migrations.AddIndex(
            model_name="marcmatchcandidate",
            index=models.Index(
                fields=["import_record", "confidence"],
                name="marc_marcma_import__92f726_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marcmatchcandidate",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="marc_marcma_target__601a9f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marcmatchcandidate",
            unique_together={("import_record", "target_type", "target_id", "match_rule")},
        ),
    ]
