# Generated by Django 5.2.15 on 2026-06-28 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circulation", "0001_initial"),
        ("holdings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchCalendarException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=255)),
                ("is_closed", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CirculationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("name", models.CharField(max_length=255)),
                ("patron_type", models.CharField(blank=True, max_length=64)),
                ("resource_type", models.CharField(blank=True, max_length=32)),
                ("loan_period_days", models.PositiveIntegerField(default=14)),
                ("renewal_period_days", models.PositiveIntegerField(default=14)),
                ("max_renewals", models.PositiveIntegerField(default=2)),
                ("max_open_loans", models.PositiveIntegerField(default=20)),
                ("max_holds", models.PositiveIntegerField(default=10)),
                ("allow_holds", models.BooleanField(default=True)),
                ("allow_renewal_when_holds", models.BooleanField(default=False)),
                ("hold_shelf_days", models.PositiveIntegerField(default=7)),
                ("overdue_grace_days", models.PositiveIntegerField(default=0)),
                (
                    "overdue_fee_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "max_overdue_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "fee_block_threshold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="FeeWaiver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("waived_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("transfer", "Transfer"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=16,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(blank=True, max_length=128)),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("posted", "Posted"), ("voided", "Voided")],
                        default="posted",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name="finefee",
            name="assessed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finefee",
            name="assessed_through",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finefee",
            name="balance_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="finefee",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("overdue", "Overdue"),
                    ("lost_item", "Lost item"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="finefee",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="finefee",
            name="original_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="finefee",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("paid", "Paid"),
                    ("waived", "Waived"),
                    ("voided", "Voided"),
                ],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="finefee",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="finefee",
            index=models.Index(
                fields=["patron", "status"], name="circulation_patron__e3fb6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finefee",
            index=models.Index(
                fields=["fee_type", "status"], name="circulation_fee_typ_f77a2f_idx"
            ),
        ),
        migrations.AddField(
            model_name="branchcalendarexception",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_exceptions",
                to="holdings.branch",
            ),
        ),
        migrations.AddField(
            model_name="circulationpolicy",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circulation_policies",
                to="holdings.branch",
            ),
        ),
        migrations.AddField(
            model_name="circulationpolicy",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circulation_policies",
                to="holdings.location",
            ),
        ),
        migrations.AddField(
            model_name="feewaiver",
            name="fine_fee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="waivers",
                to="circulation.finefee",
            ),
        ),
        migrations.AddField(
            model_name="feewaiver",
            name="waived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="circulation_fee_waivers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="patron",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="circulation.patron",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_circulation_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="fine_fee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_allocations",
                to="circulation.finefee",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="circulation.payment",
            ),
        ),
        migrations.AddIndex(
            model_name="branchcalendarexception",
            index=models.Index(
                fields=["branch", "date", "is_closed"],
                name="circulation_branch__fcf14d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branchcalendarexception",
            unique_together={("branch", "date")},
        ),
        migrations.AddIndex(
            model_name="circulationpolicy",
            index=models.Index(
                fields=["is_active", "priority"], name="circulation_is_acti_1bebd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="circulationpolicy",
            index=models.Index(
                fields=["patron_type", "resource_type"],
                name="circulation_patron__a35bee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["patron", "received_at"], name="circulation_patron__2837ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="circulation_status_9f1e44_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="paymentallocation",
            unique_together={("payment", "fine_fee")},
        ),
    ]
