# Generated by Django 5.2.15 on 2026-06-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "circulation",
            "0002_branchcalendarexception_circulationpolicy_feewaiver_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="anonymized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
