# Generated by Django 5.2.15 on 2026-06-28 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("holdings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SerialTitle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=512)),
                ("issn", models.CharField(blank=True, max_length=32)),
                ("frequency", models.CharField(blank=True, max_length=128)),
                ("publication_pattern", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "instance",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="serial_title",
                        to="catalog.instance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("enumeration", models.CharField(blank=True, max_length=128)),
                ("chronology", models.CharField(blank=True, max_length=128)),
                ("expected_at", models.DateField(blank=True, null=True)),
                ("received_at", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expected", "Expected"),
                            ("received", "Received"),
                            ("missing", "Missing"),
                            ("bound", "Bound"),
                        ],
                        default="expected",
                        max_length=16,
                    ),
                ),
                (
                    "holding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="holdings.holding",
                    ),
                ),
                (
                    "serial_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="serials.serialtitle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "expected_at"],
                        name="serials_iss_status_63b5b7_idx",
                    )
                ],
            },
        ),
    ]
