# Generated by Django 5.2.15 on 2026-06-28 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authorities", "0001_initial"),
        ("vocabularies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expression",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=512)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("expression_note", models.TextField(blank=True)),
                (
                    "translators",
                    models.ManyToManyField(
                        blank=True, to="authorities.authorityrecord"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("serial", "Serial"),
                            ("map", "Map"),
                            ("score", "Score"),
                            ("av", "Audio/visual"),
                            ("digital", "Digital"),
                            ("mixed", "Mixed material"),
                        ],
                        default="book",
                        max_length=32,
                    ),
                ),
                ("title_statement", models.CharField(max_length=1024)),
                ("variant_titles", models.JSONField(blank=True, default=list)),
                (
                    "responsibility_statement",
                    models.CharField(blank=True, max_length=1024),
                ),
                ("edition_statement", models.CharField(blank=True, max_length=512)),
                ("publication_place", models.CharField(blank=True, max_length=255)),
                ("publisher", models.CharField(blank=True, max_length=512)),
                ("publication_date", models.CharField(blank=True, max_length=128)),
                ("extent", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("media_type", models.CharField(blank=True, max_length=128)),
                ("carrier_type", models.CharField(blank=True, max_length=128)),
                ("identifiers", models.JSONField(blank=True, default=list)),
                ("notes", models.JSONField(blank=True, default=list)),
                (
                    "classifications",
                    models.ManyToManyField(
                        blank=True, to="vocabularies.classificationnumber"
                    ),
                ),
                (
                    "expression",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="catalog.expression",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstanceContributor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("role", models.CharField(blank=True, max_length=128)),
                ("marc_tag", models.CharField(blank=True, max_length=8)),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authorities.authorityrecord",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.instance",
                    ),
                ),
            ],
            options={
                "unique_together": {("instance", "authority", "role", "marc_tag")},
            },
        ),
        migrations.AddField(
            model_name="instance",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                through="catalog.InstanceContributor",
                to="authorities.authorityrecord",
            ),
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("primary_title", models.CharField(max_length=512)),
                ("original_title", models.CharField(blank=True, max_length=512)),
                ("form", models.CharField(blank=True, max_length=128)),
                ("date", models.CharField(blank=True, max_length=64)),
                ("language_hint", models.CharField(blank=True, max_length=16)),
                ("summary", models.TextField(blank=True)),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True, to="vocabularies.vocabularyterm"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="instance",
            name="work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="catalog.work",
            ),
        ),
        migrations.AddField(
            model_name="expression",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expressions",
                to="catalog.work",
            ),
        ),
        migrations.CreateModel(
            name="BibliographicRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=128)),
                ("control_number", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                            ("suppressed", "Suppressed"),
                        ],
                        default="imported",
                        max_length=24,
                    ),
                ),
                ("encoding_level", models.CharField(blank=True, max_length=8)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bib_records",
                        to="catalog.instance",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bib_records",
                        to="catalog.work",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkAuthorityLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("creator", "Creator"),
                            ("subject", "Subject"),
                            ("related_work", "Related work"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "relationship_designator",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authorities.authorityrecord",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.work"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="work",
            name="authorities",
            field=models.ManyToManyField(
                blank=True,
                through="catalog.WorkAuthorityLink",
                to="authorities.authorityrecord",
            ),
        ),
        migrations.AddIndex(
            model_name="instance",
            index=models.Index(
                fields=["resource_type"], name="catalog_ins_resourc_7349a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instance",
            index=models.Index(
                fields=["title_statement"], name="catalog_ins_title_s_fccfb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instance",
            index=models.Index(
                fields=["publisher"], name="catalog_ins_publish_7aca43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instance",
            index=models.Index(
                fields=["publication_date"], name="catalog_ins_publica_f09dbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expression",
            index=models.Index(
                fields=["language", "content_type"],
                name="catalog_exp_languag_d607db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bibliographicrecord",
            index=models.Index(fields=["status"], name="catalog_bib_status_fb1c08_idx"),
        ),
        migrations.AddIndex(
            model_name="bibliographicrecord",
            index=models.Index(
                fields=["control_number"], name="catalog_bib_control_79214f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bibliographicrecord",
            unique_together={("source", "control_number")},
        ),
        migrations.AlterUniqueTogether(
            name="workauthoritylink",
            unique_together={("work", "authority", "role", "relationship_designator")},
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["primary_title"], name="catalog_wor_primary_172288_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["date"], name="catalog_wor_date_532709_idx"),
        ),
    ]
