# Generated by Django 5.2.15 on 2026-06-28 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("authorized", "Authorized"), ("variant", "Variant")],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=512)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("script", models.CharField(blank=True, max_length=32)),
                ("romanization", models.CharField(blank=True, max_length=128)),
                ("source_field", models.CharField(blank=True, max_length=32)),
                ("is_preferred", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AuthorizedAccessPoint",
            fields=[],
            options={
                "verbose_name": "Authorized access point",
                "verbose_name_plural": "Authorized access points",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("authorities.accesspoint",),
        ),
        migrations.CreateModel(
            name="VariantAccessPoint",
            fields=[],
            options={
                "verbose_name": "Variant access point",
                "verbose_name_plural": "Variant access points",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("authorities.accesspoint",),
        ),
        migrations.CreateModel(
            name="AuthorityRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "authority_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("family", "Family"),
                            ("corporate_body", "Corporate body"),
                            ("conference", "Conference"),
                            ("work_title", "Work or uniform title"),
                            ("subject", "Subject"),
                            ("genre", "Genre"),
                            ("place", "Place"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
                ("control_number", models.CharField(blank=True, max_length=128)),
                ("entity_uri", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisional"),
                            ("authorized", "Authorized"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="provisional",
                        max_length=24,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["authority_type", "status"],
                        name="authorities_authori_7f4c00_idx",
                    ),
                    models.Index(
                        fields=["entity_uri"], name="authorities_entity__c02bba_idx"
                    ),
                ],
                "unique_together": {("source", "control_number")},
            },
        ),
        migrations.AddField(
            model_name="accesspoint",
            name="authority",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_points",
                to="authorities.authorityrecord",
            ),
        ),
        migrations.CreateModel(
            name="AuthorityRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("equivalent", "Equivalent"),
                            ("broader", "Broader"),
                            ("narrower", "Narrower"),
                            ("related", "Related"),
                            ("earlier_name", "Earlier name"),
                            ("later_name", "Later name"),
                            ("see", "See"),
                            ("see_also", "See also"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="authorities.authorityrecord",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="authorities.authorityrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("scheme", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=256)),
                ("uri", models.URLField(blank=True)),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identifiers",
                        to="authorities.authorityrecord",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="accesspoint",
            index=models.Index(
                fields=["kind", "label"], name="authorities_kind_c28940_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesspoint",
            index=models.Index(
                fields=["language", "script"], name="authorities_languag_343138_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="authorityrelation",
            unique_together={("source", "target", "relation_type")},
        ),
        migrations.AlterUniqueTogether(
            name="externalidentifier",
            unique_together={("scheme", "value")},
        ),
    ]
