# Generated by Django 5.2.15 on 2026-06-28 18:36

import django.db.models.deletion
from django.db import migrations, models


def backfill_access_point_keys(apps, schema_editor):
    AccessPoint = apps.get_model("authorities", "AccessPoint")
    for access_point in AccessPoint.objects.all():
        normalized = " ".join(access_point.label.casefold().split())
        access_point.normalized_label = normalized
        access_point.sort_key = normalized
        access_point.save(update_fields=["normalized_label", "sort_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("authorities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesspoint",
            name="normalized_label",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="accesspoint",
            name="sort_key",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="authorityrecord",
            name="deprecated_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="authorityrecord",
            name="deprecated_replacement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deprecated_sources",
                to="authorities.authorityrecord",
            ),
        ),
        migrations.RunPython(backfill_access_point_keys, migrations.RunPython.noop),
    ]
