# Generated by Django 5.2.15 on 2026-06-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authorities",
            "0002_accesspoint_normalized_label_accesspoint_sort_key_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="authorityrecord",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="authorityrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("control_number", ""), _negated=True),
                fields=("source", "control_number"),
                name="unique_authority_source_control_number_when_present",
            ),
        ),
    ]
