# Generated by Django 5.2.15 on 2026-06-28 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassificationScheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("edition", models.CharField(blank=True, max_length=64)),
                ("source_uri", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ControlledVocabulary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("source_uri", models.URLField(blank=True)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("is_local", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClassificationNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(max_length=128)),
                ("caption", models.CharField(blank=True, max_length=512)),
                ("normalized", models.CharField(blank=True, max_length=128)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="vocabularies.classificationnumber",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numbers",
                        to="vocabularies.classificationscheme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CallNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("raw", models.CharField(max_length=255)),
                ("prefix", models.CharField(blank=True, max_length=64)),
                ("cutter", models.CharField(blank=True, max_length=64)),
                ("year", models.CharField(blank=True, max_length=16)),
                ("copy", models.CharField(blank=True, max_length=32)),
                (
                    "normalized_sort_key",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vocabularies.classificationnumber",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VocabularyTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(blank=True, max_length=128)),
                ("label", models.CharField(max_length=512)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("script", models.CharField(blank=True, max_length=32)),
                ("external_uri", models.URLField(blank=True)),
                ("scope_note", models.TextField(blank=True)),
                (
                    "broader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="narrower_terms",
                        to="vocabularies.vocabularyterm",
                    ),
                ),
                (
                    "related_terms",
                    models.ManyToManyField(
                        blank=True, to="vocabularies.vocabularyterm"
                    ),
                ),
                (
                    "vocabulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="vocabularies.controlledvocabulary",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="classificationnumber",
            index=models.Index(fields=["number"], name="vocabularie_number_306a36_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationnumber",
            index=models.Index(
                fields=["normalized"], name="vocabularie_normali_53cc33_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classificationnumber",
            unique_together={("scheme", "number")},
        ),
        migrations.AddIndex(
            model_name="vocabularyterm",
            index=models.Index(fields=["label"], name="vocabularie_label_b3c03b_idx"),
        ),
        migrations.AddIndex(
            model_name="vocabularyterm",
            index=models.Index(
                fields=["external_uri"], name="vocabularie_externa_0b256c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vocabularyterm",
            unique_together={
                ("vocabulary", "code"),
                ("vocabulary", "label", "language"),
            },
        ),
    ]
