# Generated by Django 5.2.15 on 2026-06-28 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title_main", models.TextField()),
                ("title_variant", models.TextField(blank=True)),
                ("creator", models.TextField(blank=True)),
                ("subject", models.TextField(blank=True)),
                ("identifiers", models.TextField(blank=True)),
                ("publisher", models.TextField(blank=True)),
                ("publication_date", models.CharField(blank=True, max_length=128)),
                ("language", models.CharField(blank=True, max_length=64)),
                ("resource_type", models.CharField(blank=True, max_length=64)),
                ("facets", models.JSONField(blank=True, default=dict)),
                ("availability", models.CharField(default="unknown", max_length=64)),
                ("full_text", models.TextField(blank=True)),
                ("indexed_at", models.DateTimeField(auto_now=True)),
                (
                    "instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_document",
                        to="catalog.instance",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resource_type", "availability"],
                        name="discovery_s_resourc_582c07_idx",
                    ),
                    models.Index(
                        fields=["publication_date"],
                        name="discovery_s_publica_2c433d_idx",
                    ),
                ],
            },
        ),
    ]
