# Generated by Django 5.2.15 on 2026-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchdocument",
            name="availability_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchdocument",
            name="cjk_tokens",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="searchdocument",
            name="normalized_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="searchdocument",
            name="year_sort",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="searchdocument",
            index=models.Index(
                fields=["year_sort"], name="discovery_s_year_so_b7d0fd_idx"
            ),
        ),
    ]
