# Generated by Django 5.2.15 on 2026-06-28 17:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=512)),
                ("dc_metadata", models.JSONField(blank=True, default=dict)),
                ("rights_statement", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("restricted", "Restricted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "oai_identifier",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                (
                    "bibliographic_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="digital_objects",
                        to="catalog.bibliographicrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("file", models.FileField(upload_to="repository/")),
                ("label", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("ocr_text", models.TextField(blank=True)),
                ("access_level", models.CharField(default="public", max_length=64)),
                (
                    "digital_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_assets",
                        to="repository.digitalobject",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="digitalobject",
            index=models.Index(fields=["status"], name="repository__status_9d3f13_idx"),
        ),
        migrations.AddIndex(
            model_name="digitalobject",
            index=models.Index(fields=["oai_identifier"], name="repository__oai_ide_daad5c_idx"),
        ),
        migrations.AddIndex(
            model_name="fileasset",
            index=models.Index(
                fields=["mime_type", "access_level"],
                name="repository__mime_ty_a215b5_idx",
            ),
        ),
    ]
