# Generated by Django 5.2.15 on 2026-06-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitalobject",
            name="oai_identifier",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
