# Generated by Django 5.2.15 on 2026-06-28 19:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "circulation",
            "0002_branchcalendarexception_circulationpolicy_feewaiver_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.SlugField(max_length=128, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("due_soon", "Due soon"),
                            ("overdue", "Overdue"),
                            ("hold_available", "Hold available"),
                            ("fine_notice", "Fine notice"),
                            ("license_expiry_staff", "License expiry staff"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In app"), ("email", "Email")],
                        max_length=16,
                    ),
                ),
                ("subject_template", models.CharField(max_length=255)),
                ("body_template", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["notification_type", "channel", "is_active"],
                        name="notificatio_notific_555df3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("due_soon", "Due soon"),
                            ("overdue", "Overdue"),
                            ("hold_available", "Hold available"),
                            ("fine_notice", "Fine notice"),
                            ("license_expiry_staff", "License expiry staff"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In app"), ("email", "Email")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "patron",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="circulation.patron",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_user", "status", "created_at"],
                        name="notificatio_recipie_08d144_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "channel", "status"],
                        name="notificatio_notific_57cccc_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="notificatio_target__1f2fb1_idx",
                    ),
                ],
            },
        ),
    ]
